# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcsecond', '0002_auto_20150719_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='age',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='albedo',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='albedo',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='angle',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='angle',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='angulardistance',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='angulardistance',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='distance',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='distance',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='eccentricity',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='eccentricity',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='ellipseaxis',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='ellipseaxis',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='flux',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='flux',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='gravity',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='gravity',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='julianday',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='julianday',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='mass',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='mass',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='metallicity',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='metallicity',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='parallax',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='parallax',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='radius',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='radius',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='error_up',
            new_name='error_min',
        ),
        migrations.RenameField(
            model_name='velocity',
            old_name='error_down',
            new_name='error_max',
        ),
        migrations.RenameField(
            model_name='velocity',
            old_name='error_up',
            new_name='error_min',
        ),
    ]
